#!/bin/sh

pandoc \
  --from markdown+autolink_bare_uris+implicit_figures+hard_line_breaks \
  --template /opt/eisvogel/eisvogel.tex --listings --standalone --number-sections \
  --filter pandoc-citeproc \
  "$@"
